In [1]:
#!pip install gensim

In [2]:
import gensim.downloader as api
word_vectors = api.load("word2vec-google-news-300")

In [10]:
print(word_vectors['computer'])

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [12]:
len(word_vectors)

3000000

<h2>King + Woman - Man = ?</h2>

In [24]:
positive = ['king', 'woman']
negative = ['man']
topn = 10

print(word_vectors.most_similar(positive, negative, topn))

[('queen', 0.7118192911148071), ('monarch', 0.6189674735069275), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321243286133), ('kings', 0.5236844420433044), ('Queen_Consort', 0.5235945582389832), ('queens', 0.5181134343147278), ('sultan', 0.5098593235015869), ('monarchy', 0.5087411403656006)]


In [27]:
print(word_vectors.most_similar("tower", topn=5))

[('towers', 0.8531749844551086), ('skyscraper', 0.6417425870895386), ('Tower', 0.639177143573761), ('spire', 0.5946877598762512), ('responded_Understood_Atlasjet', 0.5931612849235535)]


In [43]:
print(word_vectors.similarity("man", "woman"))
print(word_vectors.similarity("king", "queen"))
print(word_vectors.similarity("lion", "tiger"))
print(word_vectors.similarity("boy", "girl"))
print(word_vectors.similarity("apple", "fruit"))
print(word_vectors.similarity("samsung", "nokia"))
print(word_vectors.similarity("paper", "scissor"))

0.76640123
0.6510956
0.51210403
0.8543272
0.6410147
0.70766187
0.1708892


In [47]:
import numpy as np

word1 = 'man'
word2 = 'woman'

word3 = 'semiconductor'
word4 = 'grasshopper'

word5 = 'nephew'
word6 = 'niece'

vec_diff1 = word_vectors[word1] - word_vectors[word2]
vec_diff2 = word_vectors[word3] - word_vectors[word4]
vec_diff3 = word_vectors[word5] - word_vectors[word6]

magnitude_of_diff1 = np.linalg.norm(vec_diff1)
magnitude_of_diff2 = np.linalg.norm(vec_diff2)
magnitude_of_diff3 = np.linalg.norm(vec_diff3)

print(magnitude_of_diff1)
print(magnitude_of_diff2)
print(magnitude_of_diff3)

1.727951
4.987503
1.9557793


<h2>Creating Token Embeddings</h2>

In [52]:
import torch
input_ids = torch.tensor([2, 3, 5, 1])

In [92]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [94]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [96]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [98]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [3]:
# import scipy
# print(scipy.__version__)

# pip install --upgrade gensim numpy

# import gensim.downloader as api
# print(api.BASE_DIR)

# to get the location where the model is downloaded in order to delete to empty space